application/urls.py
from django.contrib import admin
from django.urls import path
from application.views import *

app_name = "application"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index_view , name='index'),
    path("contact", contact_view , name='contact'),
    path("about", about_view , name='about')
]

blog/urls.py
from django.contrib import admin
from django.urls import path
from application.views import *
from blog.views import *

app_name = "blog"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', blog_index_view, name="index"),
    path('<int:pid>', blog_single_view, name='single'),
    #path('<str:name>/<str:lastname>/gender/<str:gender>', test_view, name='test') #url haye ma mitoone ham static bashe ham dynamic
    #path('post-<int:pid>', test_view, name='test')
    path('test',test_view,name='test')

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('application.urls')),
    path('blog/', include('blog.urls')),

]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

application/models.py
from email.policy import default
from re import T
from django.db import models
from django.contrib.auth.models import User


# Create your models here.

class Category(models.Model):

    
    name=models.CharField(max_length=250,default='h')
    
    def __str__(self):
        return self.name


class post(models.Model):

    #category
    #tag
    category=models.ManyToManyField(Category)   #baraye ManyToManyField niaz nist null tarif konim.
    image=models.ImageField(upload_to='blog/',default='default.jpg')
    author=models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    title=models.CharField(max_length=240,default="hi")
    content=models.TextField()   #TextField niazi be default nadare.
    counted_views=models.IntegerField(default=0)
    status=models.BooleanField(default=False)
    published_date=models.DateTimeField(null=True)
    created_date=models.DateTimeField(auto_now_add=True)
    updated_date=models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ['created_date'] #ba incode kollan ordering barasase created_date anjam mishe.
        #verbose_name = "pizza"       az verbose_name va verbos_name_plural zamani estefade mishavad ke bekhahim yek kalamaro avaz konim
        #verbose_name_plural = "stories" 


    #bedoone code zir object post ha ba id hayeshan namayesh dade mishavad.
    def __str__(self):
       return self.title
       # return " {} + {} + {} " .format(self.title,self.id,self.status) 

    def snippets(self):
        return self.content[:200] + '...'











class contact(models.Model):

    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-created_date',) #agar az tuple tak ozvi estefade mikonim hamtan tahesh  , bezarim. 

    def __str__(self):
       return self.name 






    
    
    

blog/models.py
from django.db import models

# Create your models here.

class post(models.Model):

    #category
    #tag
    title=models.CharField(max_length=240,default="hi")
    content=models.CharField(max_length=230,default="hello")
    counted_views=models.IntegerField(default=0)
    status=models.BooleanField(default=False)
    published_date=models.DateTimeField(null=True)
    created_date=models.DateTimeField(auto_now_add=True)
    updated_date=models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ['created_date'] #ba incode kollan ordering barasase created_date anjam mishe.
        #verbose_name = "pizza"       az verbose_name va verbos_name_plural zamani estefade mishavad ke bekhahim yek kalamaro avaz konim
        #verbose_name_plural = "stories" 


    #bedoone code zir object post ha ba id hayeshan namayesh dade mishavad.
    def __str__(self):
       return self.title
       # return " {} + {} + {} " .format(self.title,self.id,self.status) 



    

application/views.py
from django.shortcuts import render
# Create your views here.
from django.http import HttpResponse,JsonResponse



def index_view(request):
    return render(request, 'application/index.html')       #In this code we return a html code


def about_view(request):
    return render(request, 'application/about.html')      #In this code we return the json code



def contact_view(request):
    return render(request, 'application/contact.html')

blog/views.py
from django.shortcuts import render,get_object_or_404
from application.models import post

# Create your views here.

def blog_index_view(request):
    posts=post.objects.filter(status=1)
    context={'posts':posts}
    return render (request, 'blog/blog-home.html',context)

def blog_single_view(request,pid):
    p = get_object_or_404(post,pk=pid,status=1)   #dar inja agar hamchin posti vojood nadashte bashe error 404 mide.
    context={'post':p}
    return render (request, 'blog/blog-single.html',context)

#def test_view(request,pid):
    #p = post.objects.get(id=pid)        #dar inja agar hamchin posti vojood nadashte bashe error doesnt exist mide.
    posts= post.objects.filter(status=1)
    p = get_object_or_404(posts,pk=pid)   #dar inja agar hamchin posti vojood nadashte bashe error 404 mide.
    context={'post':p}
    #context={'name':name,'lastname':lastname,'gender':gender}
    return render (request, 'test.html',context)

def test_view(request):
    return render(request,'test.html') 

application/templates/application/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>contact</title>
</head>
<body>
    <h1>contact</h1>
</body>
</html>

application/templates/application/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home</title>
</head>
<body>
    <h1>Home</h1>
</body>
</html>

templates/application/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>test</title>
</head>
<body>
    <h1>Hello {{name}} {{lastname}}</h1>
</body>
</html>

templates/base.html
{% load static %}
<! ba code bala file haye folder static load mishe va dar template az tarighe href azashoon estefade mishe.> >
	<!DOCTYPE html>
	<html lang="zxx" class="no-js>
	<head>
		<!-- Mobile Specific Meta -->
		<meta name=" viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<!-- Favicon-->
	<link rel="shortcut icon" href="{% static 'img/fav.png">
	<!-- Author Meta -->
	<meta name="author" content="colorlib">
	<!-- Meta Description -->
	<meta name="description" content="">
	<!-- Meta Keyword -->
	<meta name="keywords" content="">
	<!-- meta character set -->
	<meta charset="UTF-8">
	<!-- Site Title -->
	<title>Travel</title>

	<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet">
	<!--
			CSS
			============================================= -->
	<link rel="stylesheet" href="{% static 'css/linearicons.css' %}">
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
	<link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
	"
	<link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
	<link rel="stylesheet" href="{% static 'css/nice-select.css' %}">
	<link rel="stylesheet" href="{% static 'css/animate.min.css' %}">
	<link rel="stylesheet" href="{% static 'css/owl.carousel.css' %}">
	<link rel="stylesheet" href="{% static 'css/main.css' %}">
	</head>

	<body>
		<header id="header">
			<div class="header-top">
				<div class="container">
					<div class="row align-items-center">
						<div class="col-lg-6 col-sm-6 col-6 header-top-left">
							<ul>
								<li><a href="#">Visit Us</a></li>
								<li><a href="#">Buy Tickets</a></li>
							</ul>
						</div>
						<div class="col-lg-6 col-sm-6 col-6 header-top-right">
							<div class="header-social">
								<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-dribbble"></i></a>
								<a href="#"><i class="fa fa-behance"></i></a>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="container main-menu">
				<div class="row align-items-center justify-content-between d-flex">
					<div id="logo">
						<a href="{% url 'application:index' %}"><img src="{% static 'img/logo.png" alt=""
								title="" /></a>
					</div>
					<nav id="nav-menu-container">
						<ul class="nav-menu">
							<li><a href="{% url 'application:index' %}">Home</a></li>
							<li><a href="{% url 'application:about' %}">About</a></li>	
							<li><a href="{% url 'blog:index' %}">Blog</a></li>
								
						</li>
						<li class="menu-has-children"><a href="">Pages</a>
							<ul>
								<li><a href="#">Elements</a></li>
								<li class="menu-has-children"><a href="">Level 2 </a>
									<ul>
										<li><a href="#">Item One</a></li>
										<li><a href="#">Item Two</a></li>
									</ul>
								</li>
							</ul>
						</li>
							<li><a href="{% url 'application:contact' %}">Contact</a></li>
						</ul>
					</nav><!-- #nav-menu-container -->
				</div>
			</div>
		</header><!-- #header -->



		{% block content %}



		{% endblock %}


		<!-- start footer Area -->
		<footer class="footer-area section-gap">
			<div class="container">

				<div class="row">
					<div class="col-lg-3  col-md-6 col-sm-6">
						<div class="single-footer-widget">
							<h6>About Agency</h6>
							<p>
								The world has become so fast paced that people don’t want to stand by reading a page of
								information, they would much rather look at a presentation and understand the message.
								It has come to a point
							</p>
						</div>
					</div>
					<div class="col-lg-3 col-md-6 col-sm-6">
						<div class="single-footer-widget">
							<h6>Navigation Links</h6>
							<div class="row">
								<div class="col">
									<ul>
										<li><a href="#">Home</a></li>
										<li><a href="#">Feature</a></li>
										<li><a href="#">Services</a></li>
										<li><a href="#">Portfolio</a></li>
									</ul>
								</div>
								<div class="col">
									<ul>
										<li><a href="#">Team</a></li>
										<li><a href="#">Pricing</a></li>
										<li><a href="#">Blog</a></li>
										<li><a href="#">Contact</a></li>
									</ul>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-3  col-md-6 col-sm-6">
						<div class="single-footer-widget">
							<h6>Newsletter</h6>
							<p>
								For business professionals caught between high OEM price and mediocre print and graphic
								output.
							</p>
							<div id="mc_embed_signup">
								<form target="_blank"
									action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01"
									method="get" class="subscription relative">
									<div class="input-group d-flex flex-row">
										<input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''"
											onblur="this.placeholder = 'Email Address '" required="" type="email">
										<button class="btn bb-btn"><span class="lnr lnr-location"></span></button>
									</div>
									<div class="mt-10 info"></div>
								</form>
							</div>
						</div>
					</div>
					<div class="col-lg-3  col-md-6 col-sm-6">
						<div class="single-footer-widget mail-chimp">
							<h6 class="mb-20">InstaFeed</h6>
							<ul class="instafeed d-flex flex-wrap">
								<li><img src="{% static 'img/i1.jpg' %}" alt=""></li>
								<li><img src="{% static 'img/i2.jpg' %}" alt=""></li>
								<li><img src="{% static 'img/i3.jpg' %}" alt=""></li>
								<li><img src="{% static 'img/i4.jpg' %}" alt=""></li>
								<li><img src="{% static 'img/i5.jpg' %}" alt=""></li>
								<li><img src="{% static 'img/i6.jpg' %}" alt=""></li>
								<li><img src="{% static 'img/i7.jpg' %}" alt=""></li>
								<li><img src="{% static 'img/i8.jpg' %}" alt=""></li>
							</ul>
						</div>
					</div>
				</div>

				<div class="row footer-bottom d-flex justify-content-between align-items-center">
					<p class="col-lg-8 col-sm-12 footer-text m-0">
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						Copyright &copy;
						<script>document.write(new Date().getFullYear());</script> All rights reserved | This template
						is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com"
							target="_blank">Colorlib</a>
						<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
					</p>
					<div class="col-lg-4 col-sm-12 footer-social">
						<a href="#"><i class="fa fa-facebook"></i></a>
						<a href="#"><i class="fa fa-twitter"></i></a>
						<a href="#"><i class="fa fa-dribbble"></i></a>
						<a href="#"><i class="fa fa-behance"></i></a>
					</div>
				</div>
			</div>
		</footer>
		<!-- End footer Area -->

		<script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
		<script src="{% static 'js/popper.min.js' %}"></script>
		<script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>
		<script src="https://maps.googleapis.com/maps/api/jskey=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
		<script src="{% static 'js/jquery-ui.js' %}"></script>
		<script src="{% static 'js/easing.min.js' %}"></script>
		<script src="{% static 'js/hoverIntent.js' %}"></script>
		<script src="{% static 'js/superfish.min.js' %}"></script>
		<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
		<script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
		<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
		<script src="{% static 'js/owl.carousel.min.js' %}"></script>
		<script src="{% static 'js/mail-script.js' %}"></script>
		<script src="{% static 'js/main.js' %}"></script>
	</body>

	</html>

templates/blog/blog-ads.html
{% load static %}
<div class="single-sidebar-widget ads-widget">
    <a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt=""></a>
</div>

templates/blog/blog-single.html
{% extends "base.html" %}
{% load static %}
{% load blog_tags %}
{% load application_tags %}

{% block content %}

<!-- start banner Area -->
<section class="relative about-banner">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					{{post.title}}
				</h1>
				<p class="text-white link-nav"><a href="{% url 'application:index' %}">Home </a> <span
						class="lnr lnr-arrow-right"></span><a href="{% url 'blog:index' %}">Blog </a> <span
						class="lnr lnr-arrow-right"></span>{{post.title}}</p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start post-content Area -->
<section class="post-content-area single-post-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 posts-list">
				<div class="single-post row">
					<div class="col-lg-12">
						<div class="feature-img">
							<img class="img-fluid" src="{% static 'img/blog/feature-img1.jpg'' %}" alt="">
						</div>
					</div>
					<div class="col-lg-3  col-md-3 meta-details">
						<ul class="tags">
							<li><a href="#">Food,</a></li>
							<li><a href="#">Technology,</a></li>
							<li><a href="#">Politics,</a></li>
							<li><a href="#">Lifestyle</a></li>
						</ul>
						<div class="user-details row">
							<p class="user-name col-lg-12 col-md-12 col-6"><a href="#">Mark wiens</a> <span
									class="lnr lnr-user"></span></p>
							<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published_date | date:" d M Y
									"}}</a> <span class="lnr lnr-calendar-full"></span></p>
							<p class="view col-lg-12 col-md-12 col-6"><a href="#">1.2M Views</a> <span
									class="lnr lnr-eye"></span></p>
							<p class="comments col-lg-12 col-md-12 col-6"><a href="#">06 Comments</a> <span
									class="lnr lnr-bubble"></span></p>
							<ul class="social-links col-lg-12 col-md-12 col-6">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-github"></i></a></li>
								<li><a href="#"><i class="fa fa-behance"></i></a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-9 col-md-9">
						<h3 class="mt-20 mb-20">{{post.title}}</h3>

						<p class="excert">
							{{post.content}}
						</p>

					</div>

				</div>
				<div class="navigation-area">
					<div class="row">
						<div
							class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
							<div class="thumb">
								<a href="#"><img class="img-fluid" src="{% static 'img/blog/prev.jpg'' %}" alt=""></a>
							</div>
							<div class="arrow">
								<a href="#"><span class="lnr text-white lnr-arrow-left"></span></a>
							</div>
							<div class="detials">
								<p>Prev Post</p>
								<a href="#">
									<h4>Space The Final Frontier</h4>
								</a>
							</div>
						</div>
						<div
							class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
							<div class="detials">
								<p>Next Post</p>
								<a href="#">
									<h4>Telescopes 101</h4>
								</a>
							</div>
							<div class="arrow">
								<a href="#"><span class="lnr text-white lnr-arrow-right"></span></a>
							</div>
							<div class="thumb">
								<a href="#"><img class="img-fluid" src="{% static 'img/blog/next.jpg'' %}" alt=""></a>
							</div>
						</div>
					</div>
				</div>
				<div class="comments-area">
					<h4>05 Comments</h4>
					<div class="comment-list">
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{% static 'img/blog/c1.jpg'' %}" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">Emilly Blunt</a></h5>
									<p class="date">December 4, 2017 at 3:12 pm </p>
									<p class="comment">
										Never say goodbye till the end comes!
									</p>
								</div>
							</div>
							<div class="reply-btn">
								<a href="" class="btn-reply text-uppercase">reply</a>
							</div>
						</div>
					</div>
					<div class="comment-list left-padding">
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{% static 'img/blog/c2.jpg'' %}" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">Elsie Cunningham</a></h5>
									<p class="date">December 4, 2017 at 3:12 pm </p>
									<p class="comment">
										Never say goodbye till the end comes!
									</p>
								</div>
							</div>
							<div class="reply-btn">
								<a href="" class="btn-reply text-uppercase">reply</a>
							</div>
						</div>
					</div>
					<div class="comment-list left-padding">
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{% static 'img/blog/c3.jpg'' %}" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">Annie Stephens</a></h5>
									<p class="date">December 4, 2017 at 3:12 pm </p>
									<p class="comment">
										Never say goodbye till the end comes!
									</p>
								</div>
							</div>
							<div class="reply-btn">
								<a href="" class="btn-reply text-uppercase">reply</a>
							</div>
						</div>
					</div>
					<div class="comment-list">
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{% static 'img/blog/c4.jpg'' %}" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">Maria Luna</a></h5>
									<p class="date">December 4, 2017 at 3:12 pm </p>
									<p class="comment">
										Never say goodbye till the end comes!
									</p>
								</div>
							</div>
							<div class="reply-btn">
								<a href="" class="btn-reply text-uppercase">reply</a>
							</div>
						</div>
					</div>
					<div class="comment-list">
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{% static 'img/blog/c5.jpg' %}" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">Ina Hayes</a></h5>
									<p class="date">December 4, 2017 at 3:12 pm </p>
									<p class="comment">
										Never say goodbye till the end comes!
									</p>
								</div>
							</div>
							<div class="reply-btn">
								<a href="" class="btn-reply text-uppercase">reply</a>
							</div>
						</div>
					</div>
				</div>
				<div class="comment-form">
					<h4>Leave a Comment</h4>
					<form>
						<div class="form-group form-inline">
							<div class="form-group col-lg-6 col-md-12 name">
								<input type="text" class="form-control" id="name" placeholder="Enter Name"
									onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
							</div>
							<div class="form-group col-lg-6 col-md-12 email">
								<input type="email" class="form-control" id="email" placeholder="Enter email address"
									onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'">
							</div>
						</div>
						<div class="form-group">
							<input type="text" class="form-control" id="subject" placeholder="Subject"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
						</div>
						<div class="form-group">
							<textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'"
								required=""></textarea>
						</div>
						<a href="#" class="primary-btn text-uppercase">Post Comment</a>
					</form>
				</div>
			</div>
			<div class="col-lg-4 sidebar-widgets">
				<div class="widget-wrap">
					<div class="single-sidebar-widget search-widget">
						<form class="search-form" action="#">
							<input placeholder="Search Posts" name="search" type="text" onfocus="this.placeholder = ''"
								onblur="this.placeholder = 'Search Posts'">
							<button type="submit"><i class="fa fa-search"></i></button>
						</form>
					</div>

					{% include 'blog/blog-writer.html' %}

					<div class="single-sidebar-widget popular-post-widget">
						<h4 class="popular-title">Popular Posts</h4>
						<div class="popular-post-list">
							<div class="single-post-list d-flex flex-row align-items-center">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/blog/pp1.jpg' %}" alt="">
								</div>
								<div class="details">
									<a href="blog-single.html">
										<h6>Space The Final Frontier</h6>
									</a>
									<p>02 Hours ago</p>
								</div>
							</div>
							<div class="single-post-list d-flex flex-row align-items-center">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/blog/pp2.jpg' %}" alt="">
								</div>
								<div class="details">
									<a href="blog-single.html">
										<h6>The Amazing Hubble</h6>
									</a>
									<p>02 Hours ago</p>
								</div>
							</div>
							<div class="single-post-list d-flex flex-row align-items-center">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/blog/pp3.jpg' %}" alt="">
								</div>
								<div class="details">
									<a href="blog-single.html">
										<h6>Astronomy Or Astrology</h6>
									</a>
									<p>02 Hours ago</p>
								</div>
							</div>
							<div class="single-post-list d-flex flex-row align-items-center">
								<div class="thumb">
									<img class="img-fluid" src="{% static 'img/blog/pp4.jpg' %}" alt="">
								</div>
								<div class="details">
									<a href="blog-single.html">
										<h6>Asteroids telescope</h6>
									</a>
									<p>02 Hours ago</p>
								</div>
							</div>
						</div>
					</div>

					{% include 'blog/blog-ads.html' %}

					<div class="single-sidebar-widget post-category-widget">
						<h4 class="category-title">Post Catgories</h4>
						<ul class="cat-list">
							<li>
								<a href="#" class="d-flex justify-content-between">
									<p>Technology</p>
									<p>37</p>
								</a>
							</li>
							<li>
								<a href="#" class="d-flex justify-content-between">
									<p>Lifestyle</p>
									<p>24</p>
								</a>
							</li>
							<li>
								<a href="#" class="d-flex justify-content-between">
									<p>Fashion</p>
									<p>59</p>
								</a>
							</li>
							<li>
								<a href="#" class="d-flex justify-content-between">
									<p>Art</p>
									<p>29</p>
								</a>
							</li>
							<li>
								<a href="#" class="d-flex justify-content-between">
									<p>Food</p>
									<p>15</p>
								</a>
							</li>
							<li>
								<a href="#" class="d-flex justify-content-between">
									<p>Architecture</p>
									<p>09</p>
								</a>
							</li>
							<li>
								<a href="#" class="d-flex justify-content-between">
									<p>Adventure</p>
									<p>44</p>
								</a>
							</li>
						</ul>
					</div>
					<div class="single-sidebar-widget newsletter-widget">
						<h4 class="newsletter-title">Newsletter</h4>
						<p>
							Here, I focus on a range of items and features that we use in life without
							giving them a second thought.
						</p>
						<div class="form-group d-flex flex-row">
							<div class="col-autos">
								<div class="input-group">
									<div class="input-group-prepend">
										<div class="input-group-text"><i class="fa fa-envelope" aria-hidden="true"></i>
										</div>
									</div>
									<input type="text" class="form-control" id="inlineFormInputGroup"
										placeholder="Enter email" onfocus="this.placeholder = ''"
										onblur="this.placeholder = 'Enter email'">
								</div>
							</div>
							<a href="#" class="bbtns">Subcribe</a>
						</div>
						<p class="text-bottom">
							You can unsubscribe at any time
						</p>
					</div>
					<div class="single-sidebar-widget tag-cloud-widget">
						<h4 class="tagcloud-title">Tag Clouds</h4>
						<ul>
							<li><a href="#">Technology</a></li>
							<li><a href="#">Fashion</a></li>
							<li><a href="#">Architecture</a></li>
							<li><a href="#">Fashion</a></li>
							<li><a href="#">Food</a></li>
							<li><a href="#">Technology</a></li>
							<li><a href="#">Lifestyle</a></li>
							<li><a href="#">Art</a></li>
							<li><a href="#">Adventure</a></li>
							<li><a href="#">Food</a></li>
							<li><a href="#">Lifestyle</a></li>
							<li><a href="#">Adventure</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
<!-- End post-content Area -->

{% endblock %}